In [6]:
import numpy as np
import random

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.random.rand(2,3)

array([[0.83261489, 0.2778987 , 0.95690672],
       [0.90383435, 0.45091969, 0.57902767]])

In [20]:
arry = np.arange(16)
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
arry.shape   # array의 형태 표시

(16,)

In [25]:
arry.dtype   # array의 데이터 타입 표시

dtype('int32')

In [27]:
arry2 = arry.astype(float)
arry2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [ ]:
바이브 코딩으로 아래의 내용을 개념과 예제로 정리하기
numpy 배열임
1. 배열의 선택
2. boolean 인덱스
3. 배열의 연산
4. 배열의 변형: Transpose 사용하기

03_Numpy(Gemini).ipynb