# NumPy 배열의 핵심 기능

NumPy는 파이썬에서 과학 계산을 위한 핵심 라이브러리입니다. 특히 다차원 배열(ndarray) 객체를 중심으로, 벡터화된 연산을 통해 매우 효율적인 데이터 처리를 가능하게 합니다.

이 노트북에서는 NumPy 배열의 주요 기능인 **선택(Indexing/Slicing)**, **불리언 인덱싱(Boolean Indexing)**, **배열 연산(Operations)**, **배열 변형(Transpose)**에 대해 알아봅니다.

## 1. 배열의 선택 (Indexing & Slicing)

NumPy 배열은 파이썬 리스트와 유사하게 인덱싱과 슬라이싱을 지원하지만, 다차원 배열에 대해 훨씬 강력하고 유연한 기능을 제공합니다.

- **인덱싱(Indexing)**: 특정 위치의 단일 원소를 선택합니다. `arr[row, col]` 형식으로 접근합니다.
- **슬라이싱(Slicing)**: 특정 범위의 원소들을 새로운 배열로 추출합니다. `arr[start:end:step]` 형식을 사용하며, 각 차원에 대해 개별적으로 적용할 수 있습니다.

In [2]:
import numpy as np

# 1차원 배열
arr1d = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
print(f"1D 배열: {arr1d}")

# 인덱싱
print(f"인덱스 3의 원소: {arr1d[3]}")

# 슬라이싱
print(f"인덱스 2부터 5까지: {arr1d[2:6]}") # 인덱스 2,3,4,5

print("-" * 30)

# 2차원 배열
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(f"2D 배열:\n{arr2d}")

# 인덱싱 (row, col)
print(f"1행 2열의 원소: {arr2d[1, 2]}") # 6

# 슬라이싱
# 첫 두 행과 1열부터 끝까지
sub_arr = arr2d[:2, 1:]
print(f"슬라이싱 된 배열:\n{sub_arr}")

1D 배열: [0 1 2 3 4 5 6 7 8 9]
인덱스 3의 원소: 3
인덱스 2부터 5까지: [2 3 4 5]
------------------------------
2D 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1행 2열의 원소: 6
슬라이싱 된 배열:
[[2 3]
 [5 6]]


## 2. 불리언 인덱싱 (Boolean Indexing)

불리언 인덱싱은 조건식을 사용하여 `True` 또는 `False` 값을 가진 불리언 배열을 만들고, 이 배열을 이용해 `True`에 해당하는 위치의 원소만 선택하는 매우 강력한 기능입니다. 데이터 필터링에 매우 유용합니다.

- **사용법**: `배열[조건식]` 형태로 사용합니다.
- **조건 결합**: 여러 조건을 결합할 때는 `&`(AND), `|`(OR) 연산자를 사용합니다. 파이썬의 `and`, `or`는 사용할 수 없습니다.

In [3]:
# 예제 배열 생성
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4) # 7x4 크기의 랜덤 데이터

print(f"이름 배열: {names}")
print(f"데이터 배열:\n{data}")

# 'Bob'에 해당하는 행의 데이터만 선택
bob_condition = (names == 'Bob')
print(f"\n'Bob' 조건 배열: {bob_condition}")
print(f"'Bob'에 해당하는 데이터:\n{data[bob_condition]}")

# 'Bob'이 아닌 모든 데이터 선택
print(f"\n'Bob'이 아닌 데이터:\n{data[~(names == 'Bob')]}")

# 여러 조건 결합 ('Bob' 또는 'Will')
multi_condition = (names == 'Bob') | (names == 'Will')
print(f"\n'Bob' 또는 'Will' 조건 배열: {multi_condition}")
print(f"'Bob' 또는 'Will'에 해당하는 데이터:\n{data[multi_condition]}")

# 데이터 자체에 조건 걸기
# data 배열에서 0보다 작은 값들을 모두 0으로 바꾸기
print(f"\n수정 전 데이터의 일부:\n{data[:2]}")
data[data < 0] = 0
print(f"0보다 작은 값을 0으로 수정한 후 데이터의 일부:\n{data[:2]}")

이름 배열: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
데이터 배열:
[[-1.2929644   0.1278675  -0.42951235 -0.79809533]
 [ 1.0788259   0.04749616  0.98878045 -0.87868647]
 [-0.41638631 -0.11890018 -0.52478364  0.78426246]
 [-0.23067843 -0.26218176  0.27664055  0.78635037]
 [ 0.37556998 -0.33364768  1.40105123  0.50812106]
 [ 0.70848999 -2.20903332 -0.77852817 -1.31432319]
 [-0.55737948 -0.97359263  1.09502265  1.49052556]]

'Bob' 조건 배열: [ True False False  True False False False]
'Bob'에 해당하는 데이터:
[[-1.2929644   0.1278675  -0.42951235 -0.79809533]
 [-0.23067843 -0.26218176  0.27664055  0.78635037]]

'Bob'이 아닌 데이터:
[[ 1.0788259   0.04749616  0.98878045 -0.87868647]
 [-0.41638631 -0.11890018 -0.52478364  0.78426246]
 [ 0.37556998 -0.33364768  1.40105123  0.50812106]
 [ 0.70848999 -2.20903332 -0.77852817 -1.31432319]
 [-0.55737948 -0.97359263  1.09502265  1.49052556]]

'Bob' 또는 'Will' 조건 배열: [ True False  True  True  True False False]
'Bob' 또는 'Will'에 해당하는 데이터:
[[-1.2929644   0.1278675  -0.4295123

## 3. 배열 연산 (Array Operations)

NumPy 배열의 가장 큰 장점 중 하나는 `for` 반복문 없이 배열 전체에 대해 빠르고 효율적인 연산을 수행할 수 있다는 점입니다. 이를 **벡터화(Vectorization)**라고 합니다.

- **기본 연산**: `+`, `-`, `*`, `/` 등 사칙연산은 배열의 각 원소별(element-wise)로 적용됩니다.
- **유니버설 함수(Universal Functions, ufunc)**: 배열의 모든 원소에 적용되는 함수들입니다. `np.sqrt()`, `np.exp()`, `np.log()`, `np.sin()` 등이 있습니다.

In [5]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(f"원본 배열:\n{arr}")

# 배열과 배열의 연산 (element-wise)
print(f"\n배열 덧셈 (arr + arr):\n{arr + arr}")
print(f"배열 곱셈 (arr * arr):\n{arr * arr}")

# 스칼라와의 연산 (broadcasting)
print(f"\n스칼라 곱셈 (arr * 2):\n{arr * 2}")
print(f"스칼라 뺄셈 (10 - arr):\n{10 - arr}")

# 유니버설 함수 사용
print(f"\n제곱근 (np.sqrt(arr)):\n{np.sqrt(arr)}")
print(f"지수 (np.exp(arr)):\n{np.exp(arr)}")

원본 배열:
[[1. 2. 3.]
 [4. 5. 6.]]

배열 덧셈 (arr + arr):
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
배열 곱셈 (arr * arr):
[[ 1.  4.  9.]
 [16. 25. 36.]]

스칼라 곱셈 (arr * 2):
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
스칼라 뺄셈 (10 - arr):
[[9. 8. 7.]
 [6. 5. 4.]]

제곱근 (np.sqrt(arr)):
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
지수 (np.exp(arr)):
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


## 4. Transpose를 사용한 배열 변형

Transpose는 배열의 행과 열을 바꾸는 작업을 의미합니다. 2차원 배열의 경우, 행은 열이 되고 열은 행이 됩니다.

- **`.T` 속성**: 배열의 `T` 속성에 접근하여 간단하게 Transpose를 수행할 수 있습니다.
- **`np.transpose()` 함수**: NumPy의 `transpose()` 함수를 사용해도 동일한 결과를 얻을 수 있습니다. 다차원 배열의 축을 더 세밀하게 제어할 때 유용합니다.

In [4]:
arr = np.arange(15).reshape((3, 5))
print(f"원본 배열 (3x5):\n{arr}")

# .T 속성을 이용한 Transpose
transposed_arr_T = arr.T
print(f"\n.T 속성으로 Transpose된 배열 (5x3):\n{transposed_arr_T}")

# np.transpose() 함수를 이용한 Transpose
transposed_arr_func = np.transpose(arr)
print(f"\nnp.transpose() 함수로 Transpose된 배열 (5x3):\n{transposed_arr_func}")

# 행렬의 내적(dot product) 계산 예시
# (m x n) . (n x p) = (m x p)
dot_product = np.dot(arr, arr.T)
print(f"\n원본 배열과 Transpose된 배열의 내적 결과 (3x3):\n{dot_product}")

원본 배열 (3x5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

.T 속성으로 Transpose된 배열 (5x3):
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

np.transpose() 함수로 Transpose된 배열 (5x3):
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

원본 배열과 Transpose된 배열의 내적 결과 (3x3):
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
